### ISSUE TITLE
Pricing Info Failure

### ISSUE THREAD

**Issue by boner-cmd** [signum-network/signum-node#523]
Dunno if I am a version behind or something, but looks like now that external sites updated to SIGNUM from BURST, all the fiat-tracking elements don't work anymore:

![image](https://user-images.githubusercontent.com/54084132/125120486-183a2480-e0b8-11eb-835f-34695f11ad25.png)

![image](https://user-images.githubusercontent.com/54084132/125120520-2425e680-e0b8-11eb-813e-dd2ce33e43a9.png)

However, it looks like Asset Score is still okay

![image](https://user-images.githubusercontent.com/54084132/125120551-3011a880-e0b8-11eb-88ff-a7fb5f04bd6a.png)

**Comment by ipr0310** [comment]
Hi!, currently the phoenix mobile update got updated
so you can download it and use it locally
https://phoenix-wallet.rocks/

The phoenix wallet in the signum node, will receive updates through the node updates

You can download the phoenix wallet and still use your node, in case you do no want to use external nodes.

**Comment by ohager** [comment]
@ipr0310 it's not the mobile wallet, but the web version. @boner-cmd It seems that it's still the 1.2.1 version. Market Info API has issues due to the rebranding that needs to stabilize throughout the crypto space. 1.2.2 has already working FIAT price estimates...I need to  check which of the current market APIs is the most reliable atm. The Asset Score was temporarily removed in 1.2.2 as Flipside Crypto hasn't been updated yet. Furthermore, they have refactored their entire metrics system to something they call "Velocity". I need to dig into and figure out the details. Their chain walker should work normally.

I recommend to download the latest desktop version of Phoenix.

https://github.com/burst-apps-team/phoenix/releases/tag/desktop-1.2.2

I close this issue as partially solved and already addressed. Thanks for reporting.

**Comment by boner-cmd** [comment]
Thanks Ohager! I expected as much but wanted to submit anyway just in case.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
