### ISSUE TITLE
Feature request: differentiate the icons of signum nodes

### ISSUE THREAD

**Issue by ipr0310** [signum-network/signum-node#575]
Hi guys!
Is there a way to differentiate the icons of signum nodes??
(Testnet and Mainet)
I do always get confused when i am clicking on these icons, is pretty annoying
![image](https://user-images.githubusercontent.com/35440957/146446659-e7d9f5ad-be21-44cf-a9a0-803a75c73433.png)

For example:
- Black circle, White logo (Main-net)
- Red circle, White logo (Test-net)

**Comment by damccull** [comment]
This would likely require operating-system specific code to change it dynamically while only providing a single release. Otherwise, it would require two separate releases, which seems redundant just to change an icon, especially since the current software works fine on both main and test nets. That means option one (OS-specific code) is the way to go for this, except that this approach requires a bunch of extra effort just to change an icon.

I vote no on this, personally, unless someone knows how to do this quickly, with cross-platform code, and without bloating the binary too much.
