### ISSUE TITLE
Get closed orders per account and/or asset

### ISSUE THREAD

**Issue by ohager** [signum-network/signum-node#657]
There is no easy way to get the closed orders for an account and/or asset

**Comment by frankTheTank72** [comment]
Right we are getting trades in the DB for each execution, but we do not know if this is 100% or only partial.

The only way to get an indication is to check the order-id from the trade. If the order-id returns "unknown" the trade is 100% executed otherwise it is a partial fill.

Error-code when 100% filled from `/api?requestType=getBidOrder`

{
  "errorCode": 4,
  "errorDescription": "Incorrect \"order\"",
  "requestProcessingTime": 20
}

**Comment by frankTheTank72** [comment]
Also we need to sum up all trades under the same order-id as we could have partial fills until we got 100%

**Comment by frankTheTank72** [comment]
Alternative is to ask for `getAccountCurrentAskOrders` and `getAccountCurrentBidOrders` and make a list of those oder-ids.
All order-ids which not match the list in getTrades are 100%.

**Comment by frankTheTank72** [comment]
closed because of #658
