### ISSUE TITLE
Remove dependency on google fonts

### ISSUE THREAD

**Issue by lordcyb3r** [signum-network/signum-node#671]
I am asking the team to consider removing the dependence on google fonts from the web wallet html pages. After looking through the html I have found that the classic wallet uses fontawesome and pulls it from local storage. The main index page and phoenix pages use google fonts pulled in with this line: `<link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,600,700" rel="stylesheet">`.

I propose to replace the google fonts with something that can be pulled locally such as fontawesome.

Google is a known tracking and ad company. They may only be choosing to collect anonymized statistics from the google fonts, but we cannot be sure. Signum is a blockchain centered around privacy so removing this is a logical step.

This is a non critical issue but something I hope will be considered.

**Comment by lordcyb3r** [comment]
> An alternative would be to fix the classic wallet and then the main index page and Phoenix wallet could simply be removed.

thats kind of a nuclear approach ngl. I think people should have the option to choose between the 2. As a side note its not gonna be that hard to replace google fonts. In-fact I did a test by blocking them in my browser and the pages look barely different, nothing broke. you had to look very very close to see a difference.

**Comment by ohager** [comment]
Fontawesome is a icon library.... Montserrat is a common font style... but yes it could be served locally... for the paranoics

**Comment by lordcyb3r** [comment]
if Montserrat isnt owned by google than yeah lets serve it locally. was just worried about google tos since its being served from their cdn in phoenix.

**Comment by Nivok-Spilkommen** [comment]
I have no issue with Phoenix, my issue is it's redundant to have two wallets.  If I'm signing into a remote wallet rather than using a local one it's because I have an emergency of some kind or I need to use a feature of the classic wallet attached to the node that is not available locally.  To anew user that is unfamiliar with our network it just presents a confusing an unnecessary choice, if they don't know the difference between the two options.  It looks like the classic wallet is being updated finally and a lot of people are happy about that so there is no longer a need for an alternative.  If Phoenix could shows the peers connected to the node etc, I'd be happy if that was the wallet but it should be one wallet, otherwise we are shipping code that is overly large, remember nodes get installed on servers where resources are not free.  I don't have a problem with Phoenix, just unnecessary choices and bloatware.

**Comment by pir8radio** [comment]
>  If Phoenix could shows the peers connected to the node etc, I'd be happy if that was the wallet but it should be one wallet, 

Phoenix always has showed connected peers no?   
![image](https://user-images.githubusercontent.com/16748696/194683669-a5b10432-ba84-4420-bc17-cd074384999f.png)

**Comment by ohager** [comment]
> I have no issue with Phoenix, my issue is it's redundant to have two wallets. If I'm signing into a remote wallet rather than using a local one it's because I have an emergency of some kind or I need to use a feature of the classic wallet attached to the node that is not available locally. To anew user that is unfamiliar with our network it just presents a confusing an unnecessary choice, if they don't know the difference between the two options. It looks like the classic wallet is being updated finally and a lot of people are happy about that so there is no longer a need for an alternative. If Phoenix could shows the peers connected to the node etc, I'd be happy if that was the wallet but it should be one wallet, otherwise we are shipping code that is overly large, remember nodes get installed on servers where resources are not free. I don't have a problem with Phoenix, just unnecessary choices and bloatware.

Remember that Phoenix was started way back in 2019 with modern tooling. For you as an user this might not make much sense, but for a dev maintaining the classic wallet actually does (ask @deleterium who is working on an update since weeks already). The former dev team left by the end of 2018 and had already initialized development on a new wallet and even started a rewrite of the node in golang (called project "Ad Aspera", which the BurstAppsTeam took over in January, 2019). The classic wallet is outdated technology and the code passed through dozen hands, and finally it became a mess (this is common for the lifecycle of a software, so no blaming here). Furthermore, the Phoenix wallet is also an easily installable desktop option for newcomers, who don't want to hassle with installing MariaDB, Java JRE, just to run a node to access the wallet. So, even in terms of security Phoenix was a step forward. Another significant outcome of the Phoenix project was the SignumJS SDK, which is being used more and more by not so hard-core devs and business partners.

Having an updated, more secure, less crowded, less messy and easily installable wallet was not the worst choice.

**Comment by ohager** [comment]
Applied on index.html in Node Software.... and openend new issue to remove from the phoenix wallet. Closing here, as this is not a problem of the node repo anymore: https://github.com/signum-network/phoenix/issues/1674
