### ISSUE TITLE
getAccount is not showing the description if it is a contract

### ISSUE THREAD

**Issue by frankTheTank72** [signum-network/signum-node#743]
getAccount is not returning the description field if the account is a contract.
Example : https://t-chain.signum.network/at/8670598290050904580
The creator of the contract returns the description - the contract itself not.

![grafik](https://user-images.githubusercontent.com/39116221/235365823-b8a1f976-6e05-4bd5-a379-af54fa07448b.png)
description is missing

![grafik](https://user-images.githubusercontent.com/39116221/235365898-8b9ba2bc-4293-49e3-82f9-2145da87f91f.png)
description is in

**Comment by jjos2372** [comment]
This is because they are stored in different tables. For contracts the name and description are on the `at` table and not on the `account` table. But we can adjust this on the API level to show the information accordingly. This would be new but not a hard-fork change. Should we introduce this in 3.7.0?

**Comment by frankTheTank72** [comment]
i would add this after 3.7.0  - @ohager  ?

**Comment by ohager** [comment]
solved
